### ISSUE TITLE
(Renode:17): Gtk-WARNING ** cannot open display: 

### ISSUE THREAD

**Issue by mtrzas** [renode/renode-docker#5]
Hi i tried to build and run renode in docker.
The command:
docker build --build-arg userId=`id -u` --build-arg groupId=`id -g` -t renode .
was succesfull but renode do not started.
When I execute:
docker run renode
this warning massage appears:
(Renode:17): Gtk-WARNING **: 16:31:08.349: cannot open display: 

I'm working with arch linux.

**Comment by pgielda** [comment]
This probably means that your Xorg server is not available inside the container.
You could try to first get something simple running inside, like xterm to test if your X server is working properly.
It might also be that your DISPLAY env variable is not set, try setting it to DISPLAY=:0 if you have a local X server running.

**Comment by pgielda** [comment]
(Btw 16:31:08.349 is the current time, not really relevant.)

**Comment by mtrzas** [comment]
Thank you very much it is working now!
